<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Marvel\Database\Models\Product;
use Marvel\Database\Models\Category;
use Marvel\Database\Models\Type;
use Marvel\Enums\ProductStatus;
use Marvel\Enums\ProductType;
use Marvel\Enums\ProductVisibilityStatus;

class ProductSeeder extends Seeder
{
    /**
     * Seed some demo products for existing categories (e.g. women).
     *
     * @return void
     */
    public function run()
    {
        // Determine language to use
        $language = defined('DEFAULT_LANGUAGE') ? DEFAULT_LANGUAGE : 'en';

        // Attach products to the "women" category if it exists
        $category = Category::where('slug', 'women')->where('language', $language)->first();

        if (!$category) {
            // Nothing to do if the category is missing
            return;
        }

        // Ensure we have at least one Type for products
        $type = Type::first();
        if (!$type) {
            $type = Type::create([
                'name'      => 'Default Type',
                'slug'      => 'default-type',
                'icon'      => null,
                'images'    => null,
                'language'  => $language,
                'settings'  => null,
            ]);
        }

        $products = [
            [
                'name'        => 'Demo Women Product 1',
                'description' => 'Demo product for the women category.',
                'price'       => 49.99,
                'sale_price'  => 39.99,
                'sku'         => 'DEMO-WOMEN-1',
            ],
            [
                'name'        => 'Demo Women Product 2',
                'description' => 'Another demo product for the women category.',
                'price'       => 79.00,
                'sale_price'  => null,
                'sku'         => 'DEMO-WOMEN-2',
            ],
            [
                'name'        => 'Demo Women Product 3',
                'description' => 'Sample item to verify infinite scroll and grids.',
                'price'       => 29.50,
                'sale_price'  => 24.99,
                'sku'         => 'DEMO-WOMEN-3',
            ],
        ];

        foreach ($products as $data) {
            $product = Product::create([
                'name'        => $data['name'],
                'slug'        => null, // Slug will be generated by sluggable
                'description' => $data['description'],
                'type_id'     => $type->id,
                'price'       => $data['price'],
                'sale_price'  => $data['sale_price'],
                'language'    => $language,
                'quantity'    => 100,
                'in_stock'    => true,
                'is_taxable'  => false,
                'status'      => ProductStatus::PUBLISH,
                'product_type'=> ProductType::SIMPLE,
                'unit'        => 'piece',
                'sku'         => $data['sku'],
                'image'       => null,
                'gallery'     => null,
                'video'       => null,
                'shipping_class_id' => null,
                'shop_id'     => null,
                'visibility'  => ProductVisibilityStatus::VISIBILITY_PUBLIC,
            ]);

            // Attach to the women category
            $product->categories()->syncWithoutDetaching([$category->id]);
        }
    }
}
